# Site settings
title: Code Rage
description: > # this means to ignore newlines until "baseurl:"
  The commentary of a perpetually frustrated programmer.
  Hopefully you'll find something useful here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "mgouzenko.github.io" # the base hostname & protocol for your site
github_username:  mgouzenko

# Build settings
markdown: kramdown
google_analytics: UA-52386265-2
